config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  resources :sales
  root 'sales#index'

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/sale.rb
require 'open-uri'

class Sale < ActiveRecord::Base
  validates_presence_of :url
  validates_presence_of :picture

  validates_uniqueness_of :url
  validates_uniqueness_of :picture

  scope :current_week, ->{ where("created_at > ?", 1.week.ago).order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  def index
    @sales = Sale.current_week
  end

  def show
  end

  def new
    @sale = Sale.new
  end

  def edit
  end

  def create
    superstore

    @sale = Sale.new(url: @root_url, picture: @picture, store_name: @name)
    @sale.save

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_path, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def coop
      url = "http://coopwinespiritsbeer.com/wines/weekly_specials/"
      doc = Nokogiri::HTML(open(url))
      @root = doc.at_css("#primary-content li:nth-child(2) a")
      Cloudinary::Uploader.upload(@root.first.last, :public_id => @root.text, url: @root.first.last)
      @name = "Co-op Liquor"
    end

    def superstore
      url = "http://realcanadianliquorstore.ca/"
      doc = Nokogiri::HTML(open(url))
      @root = doc.at_css("#right-flyer-container img")
      @root_url = @root.xpath('//div/a/@href').first.value
      @root_text = "Superstore Liquor - " + Date.today.to_s
      @picture = @root.xpath('//div/a/img/@src').first.value
      @name = "Superstore Liquor"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:url, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wine Sales" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">WineSales</a>

        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span1">
        </div><!--/span-->
        <div class="span10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Austin Hansen 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Wine sales for the week of <%= Date.today.beginning_of_week.to_formatted_s(:long)    %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
        <div class="picture">
          <%= link_to image_tag(sale.picture), sale.url %>
        </div>
    <% end %>
  </tbody>
</table>

<br>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @sale.url %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @sale.picture %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>